author: p000ison
database: false
description: Allows Players to trade.
main: com.p000ison.dev.trademe.TradeMe
name: TradeMe
startup: postworld
url: http://dev.bukkit.org/server-mods/trademe/
version: '1.0'
depend: [ Vault ]
commands:
  trademe:
    description: TradeMe commands.
    usage: |
           Usage:
           /<command> accept - Accepts a request.
           /<command> request <player> - requests a request.
           /<command> admin <watch/unwatch> - Allows you to watch the Players.
           /<command> deny - Denies a request.
           /<command> yes - Accepts a offer.
           /<command> no - Denies a offer. 
           /<command> offer <name> <amount> <price>- Offers an item.
           /<command> reload - reloads the config. 
permissions:
  trademe.command.accept:
    description: Alloes you to accept a request.
  trademe.command.deny:
    description: Alloes you to deny a request.
  trademe.command.admin:
    description: Alloes you to administrate players.
  trademe.command.yes:
    description: Alloes you to accept a offer.
  trademe.command.no:
    description: Alloes you to deny a offer.
  trademe.command.offer:
    description: Alloes you to do a offer.
  trademe.command.offeritem:
    description: Alloes you to do a item offer.
  trademe.command.reload:
    description: Alloes you to reload the config.
  trademe.command.request:
    description: Alloes you to request a player.
  trademe.user.*:
    description: Default Player Permissions.
    default: true
    children:
      trademe.command.accept: true
      trademe.command.deny: true
      trademe.command.yes: true
      trademe.command.no: true
      trademe.command.offer: true
      trademe.command.offeritem: true
      trademe.command.request: true
  trademe.admin.*:
    description: Default Admin Permissions.
    default: op
    children:
      trademe.user.*: true
      trademe.command.reload: true
      trademe.command.admin: true
