Settings:
  DistanceMinimum: 20.0  # Set this to 0.0 if you dont want this!
Messages:
  RequestSent: '&3Request has been sent!'
  GotRequest: '&3You got a trade request from %s.'
  OfferSent: '&3Offer has been sent!(Type: %s Amount: %s Price: %s)'
  GotOffer: '&3You got a Offer from %s (Type: %s Amount: %s Price: %s).'
  NotEnoughtItems: '&3You dont have the item.'
  AcceptRequest: '&3You accept the request.'
  NotTrading: '&3You are not trading at the moment.'
  NoRequestToTrade: '&3There is no request to trade.'
  Console: '&cConsoles can not do this.'
  Watch: '&3You are now watching.'
  UnWatch: '&3You stopped watching.'
  DenyTradeRequest: '&3You denied the request.'
  CancelTradeRequest: '&3You canceled the request.'
  DenyTrade: '&3You denied the request.'
  CancelTrade: '&3You canceled the request.'
  TooFar: '&cYou are too far away.'
  TradingWithYourself: '&cYou can not trade with yourself.'
  NotAValidPlayer: '&3%c is not a valid player.'
  AcceptOffer: '&3You accepted the offer.'
  DeniedOffer: '&3You denied the offer.'
  AcceptRequest: '&3You accepted the request.'
  Reload: '&3Config Reloaded! (%s ms).'
  OtherAcceptOffer: '&3%s accepted your offer.'
  OtherDeniedOffer: '&3%s denied your offer.'
  OtherAcceptRequest: '&3%s accepted your request.'
  OtherDenyTrade: '&3%s denied trading!'
  OtherCancelTrade: '&3%s cancelled trading!'
  OtherDenyTradeRequest: '&3%s denied the request to trade!'
  OtherCancelTradeRequest: '&3%s cancelled the request to trade!'
  NoOffer: '&cThere is no Offer to accept/deny!'
  InvalidItem: '&3%c is not a valid item!'
  PlayerNotAviable: '&c%s isnt anymore aviable!'
ConfigVersion: 1.0 # Dont edit this!